apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rebecca-test-plugin
  description: plugin test
  links:
    - title: Source
      url: https://github.com/cultureamp/rebecca-test-plugin
  tags:
    - asset-criticality-low
    - camp-sre
    - data-classification-none
  annotations:
    github.com/project-slug: rebecca-test-plugin
    github.com/team-slug: cultureamp/sre-enablement
    buildkite.com/project-slug: culture-amp/rebecca-test-plugin
spec:
  type: service
  lifecycle: experimental
  owner: sre-enablement
  generatedFrom: blank-repo-tmpl
