#!/bin/bash

set -e

org_slug=$BUILDKITE_PIPELINE_SLUG
build_number=$BUILDKITE_BUILD_NUMBER
build_id=$BUILDKITE_JOB_ID


BUILD_LOGS=$(curl -H "Authorization: Bearer bkua_2bce888b71d9d2dfe37a54fcc700f080587ad68a" \
    "https://api.buildkite.com/v2/organizations/culture-amp/pipelines/${org_slug}/builds/${build_number}/jobs/${build_id}/log")


if echo "$BUILD_LOGS" | grep -q "Circuit Breaker was triggered"; then
  echo "Pattern matched - sending user to confluence page"
else
  echo "Nothing to see here"
fi
